name: CI
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # once a week at midnight on Sunday
    - cron: "0 0 * * 0"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
  
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: default
      id: default-matrix
      uses: ./

    - name: exclude latest
      id: exclude-latest
      uses: ./
      with:
        exclude: '["3.11"]'
    
    - name: exclude 2 include 1
      id: exclude-2-include-1
      uses: ./
      with:
        exclude: '["3.11", "3.9"]'
        include: '["3.12"]'

    - name: release 2.4.3
      id: release-243
      uses: ./
      with:
        release: "2.4.3"
    
    - name: check outputs
      shell: bash
      run: |
        python utils/assert_varray.py --input ${{ steps.default-matrix.outputs.python-versions }} --target '["3.9", "3.10", "3.11"]'
        [[ "${{ steps.default-matrix.outputs.latest-python }}" == "3.11" ]] || exit 1
        python utils/assert_varray.py --input ${{ toJSON(steps.exclude-latest.outputs.python-versions) }} --target '["3.9", "3.10"]'
        [[ "${{ steps.exclude-latest.outputs.latest-python }}" == "3.10" ]] || exit 1
        python utils/assert_varray.py --input ${{ toJSON(steps.exclude-2-include-1.outputs.python-versions) }} --target '["3.10", "3.12"]'
        [[ "${{ steps.exclude-2-include-1.outputs.latest-python }}" == "3.12" ]] || exit 1
        python utils/assert_varray.py --input ${{ toJSON(steps.release-243.outputs.python-versions) }} --target '["3.8", "3.9", "3.10", "3.11"]'
        [[ "${{ steps.release-243.outputs.latest-python }}" == "3.11" ]] || exit 1
